/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RecipientType = IDL.Variant({
  'individual' : IDL.Null,
  'automatedSystem' : IDL.Null,
  'corporateClient' : IDL.Null,
  'representative' : IDL.Null,
  'teamMember' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TemplateInput = IDL.Record({
  'content' : IDL.Text,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const RecipientRecord = IDL.Record({
  'description' : IDL.Text,
  'partnerId' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'recipientType' : RecipientType,
  'sourceSystem' : IDL.Text,
});
export const ScheduleType = IDL.Variant({
  'immediate' : IDL.Null,
  'daily' : IDL.Null,
});
export const Schedule = IDL.Record({
  'id' : IDL.Text,
  'messageContent' : IDL.Text,
  'templateId' : IDL.Text,
  'runCount' : IDL.Nat,
  'lastRunTimestamp' : IDL.Opt(Time),
  'templateName' : IDL.Text,
  'recipients' : IDL.Vec(RecipientRecord),
  'scheduleType' : ScheduleType,
  'runAtTimestamp' : IDL.Opt(Time),
});
export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const PartnerBenefit = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentType = IDL.Variant({
  'bankDetails' : IDL.Null,
  'mobileNumber' : IDL.Null,
  'selfie' : IDL.Null,
  'email' : IDL.Null,
  'panCard' : IDL.Null,
  'aadhaarCard' : IDL.Null,
  'educationCertificate' : IDL.Null,
});
export const SubmittedDocument = IDL.Record({
  'id' : IDL.Text,
  'fileName' : IDL.Text,
  'fileContent' : ExternalBlob,
  'docType' : DocumentType,
  'uploadedAt' : Time,
});
export const WhatsAppTemplate = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : IDL.Opt(Time),
});
export const MessageStatus = IDL.Variant({
  'read' : IDL.Null,
  'sent' : IDL.Null,
  'delivered' : IDL.Null,
  'failed' : IDL.Null,
});
export const WhatsAppMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'content' : IDL.Text,
  'recipient' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const MetaApiConfig = IDL.Record({
  'whatsappBusinessAccountId' : IDL.Text,
  'accessToken' : IDL.Text,
  'phoneNumberId' : IDL.Text,
});
export const OfficeContactData = IDL.Record({
  'city' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const OnboardingRequirement = IDL.Record({
  'description' : IDL.Text,
  'required' : IDL.Bool,
  'docType' : DocumentType,
});
export const MetaWebhookVerificationRequest = IDL.Record({
  'challenge' : IDL.Text,
  'verifyToken' : IDL.Text,
  'mode' : IDL.Text,
});
export const MetaWebhookVerificationResponse = IDL.Record({
  'responseBody' : IDL.Text,
  'responseCode' : IDL.Nat,
});
export const WebhookVerificationLogEntry = IDL.Record({
  'request' : MetaWebhookVerificationRequest,
  'response' : MetaWebhookVerificationResponse,
  'timestamp' : Time,
});
export const WebhookVerificationStats = IDL.Record({
  'modeMismatched' : IDL.Nat,
  'logs' : IDL.Vec(WebhookVerificationLogEntry),
  'successful' : IDL.Nat,
  'failed' : IDL.Nat,
});
export const MetaPhoneNumberStatus = IDL.Record({
  'hasAnyNumberAttached' : IDL.Bool,
  'totalNumbers' : IDL.Nat,
  'testNumbers' : IDL.Nat,
  'apiStatusCode' : IDL.Nat,
  'productionNumbers' : IDL.Nat,
});
export const Example = IDL.Record({ 'body_text' : IDL.Vec(IDL.Text) });
export const TemplateComponent = IDL.Record({
  'example' : IDL.Opt(Example),
  'format' : IDL.Opt(IDL.Text),
});
export const Language = IDL.Record({ 'code' : IDL.Text, 'policy' : IDL.Text });
export const ExternalWhatsAppTemplate = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'components' : IDL.Vec(TemplateComponent),
  'language' : Language,
  'category' : IDL.Text,
});
export const MessagePayload = IDL.Record({
  'to' : IDL.Text,
  'content' : IDL.Text,
  'from' : IDL.Text,
});
export const MetaApiResponse = IDL.Record({
  'deliveryStatus' : MessageStatus,
  'metaMessageId' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TemplateUpdateInput = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'name' : IDL.Text,
});
export const WebhookVerificationOutcome = IDL.Variant({
  'modeMismatch' : IDL.Null,
  'success' : IDL.Text,
  'invalidToken' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPartnerBenefit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addRecipient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, RecipientType, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTemplate' : IDL.Func([TemplateInput], [IDL.Text], []),
  'deleteSchedule' : IDL.Func([IDL.Text], [], []),
  'deleteTemplate' : IDL.Func([IDL.Text], [], []),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllDailySchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getAllImmediateSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
  'getAllPartnerBenefits' : IDL.Func([], [IDL.Vec(PartnerBenefit)], ['query']),
  'getAllSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
  'getAllSubmittedDocuments' : IDL.Func(
      [],
      [IDL.Vec(SubmittedDocument)],
      ['query'],
    ),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(WhatsAppTemplate)], ['query']),
  'getAllWhatsAppMessages' : IDL.Func(
      [],
      [IDL.Vec(WhatsAppMessage)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMetaApiConfig' : IDL.Func([], [MetaApiConfig], []),
  'getOfficeContactData' : IDL.Func([], [OfficeContactData], ['query']),
  'getOnboardingRequirements' : IDL.Func(
      [],
      [IDL.Vec(OnboardingRequirement)],
      ['query'],
    ),
  'getRecipient' : IDL.Func([IDL.Text], [RecipientRecord], ['query']),
  'getSchedule' : IDL.Func([IDL.Text], [Schedule], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [WhatsAppTemplate], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebhookVerificationStats' : IDL.Func(
      [],
      [IDL.Opt(WebhookVerificationStats)],
      ['query'],
    ),
  'getWhatsAppAccountDetails' : IDL.Func(
      [],
      [IDL.Opt(MetaApiConfig)],
      ['query'],
    ),
  'getWhatsAppIntegrationStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getWhatsAppTokenStatus' : IDL.Func([], [IDL.Text], ['query']),
  'hasAtLeastOnePhoneNumberAttached' : IDL.Func(
      [],
      [MetaPhoneNumberStatus],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMetaTemplates' : IDL.Func([], [IDL.Vec(ExternalWhatsAppTemplate)], []),
  'listRecipients' : IDL.Func([], [IDL.Vec(RecipientRecord)], ['query']),
  'removeRecipient' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleMessage' : IDL.Func(
      [IDL.Text, IDL.Text, ScheduleType, IDL.Opt(Time)],
      [],
      [],
    ),
  'sendWhatsAppMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendWhatsAppMessageViaAPI' : IDL.Func(
      [MessagePayload],
      [MetaApiResponse],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMetaApiConfig' : IDL.Func([MetaApiConfig], [], []),
  'updateOfficeContactData' : IDL.Func([OfficeContactData], [], []),
  'updateTemplate' : IDL.Func([TemplateUpdateInput], [], []),
  'uploadDocument' : IDL.Func([DocumentType, IDL.Text, ExternalBlob], [], []),
  'verifyMetaWebhook' : IDL.Func(
      [MetaWebhookVerificationRequest],
      [WebhookVerificationOutcome],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RecipientType = IDL.Variant({
    'individual' : IDL.Null,
    'automatedSystem' : IDL.Null,
    'corporateClient' : IDL.Null,
    'representative' : IDL.Null,
    'teamMember' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TemplateInput = IDL.Record({ 'content' : IDL.Text, 'name' : IDL.Text });
  const Time = IDL.Int;
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const RecipientRecord = IDL.Record({
    'description' : IDL.Text,
    'partnerId' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'recipientType' : RecipientType,
    'sourceSystem' : IDL.Text,
  });
  const ScheduleType = IDL.Variant({
    'immediate' : IDL.Null,
    'daily' : IDL.Null,
  });
  const Schedule = IDL.Record({
    'id' : IDL.Text,
    'messageContent' : IDL.Text,
    'templateId' : IDL.Text,
    'runCount' : IDL.Nat,
    'lastRunTimestamp' : IDL.Opt(Time),
    'templateName' : IDL.Text,
    'recipients' : IDL.Vec(RecipientRecord),
    'scheduleType' : ScheduleType,
    'runAtTimestamp' : IDL.Opt(Time),
  });
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const PartnerBenefit = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentType = IDL.Variant({
    'bankDetails' : IDL.Null,
    'mobileNumber' : IDL.Null,
    'selfie' : IDL.Null,
    'email' : IDL.Null,
    'panCard' : IDL.Null,
    'aadhaarCard' : IDL.Null,
    'educationCertificate' : IDL.Null,
  });
  const SubmittedDocument = IDL.Record({
    'id' : IDL.Text,
    'fileName' : IDL.Text,
    'fileContent' : ExternalBlob,
    'docType' : DocumentType,
    'uploadedAt' : Time,
  });
  const WhatsAppTemplate = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : IDL.Opt(Time),
  });
  const MessageStatus = IDL.Variant({
    'read' : IDL.Null,
    'sent' : IDL.Null,
    'delivered' : IDL.Null,
    'failed' : IDL.Null,
  });
  const WhatsAppMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'content' : IDL.Text,
    'recipient' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const MetaApiConfig = IDL.Record({
    'whatsappBusinessAccountId' : IDL.Text,
    'accessToken' : IDL.Text,
    'phoneNumberId' : IDL.Text,
  });
  const OfficeContactData = IDL.Record({
    'city' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OnboardingRequirement = IDL.Record({
    'description' : IDL.Text,
    'required' : IDL.Bool,
    'docType' : DocumentType,
  });
  const MetaWebhookVerificationRequest = IDL.Record({
    'challenge' : IDL.Text,
    'verifyToken' : IDL.Text,
    'mode' : IDL.Text,
  });
  const MetaWebhookVerificationResponse = IDL.Record({
    'responseBody' : IDL.Text,
    'responseCode' : IDL.Nat,
  });
  const WebhookVerificationLogEntry = IDL.Record({
    'request' : MetaWebhookVerificationRequest,
    'response' : MetaWebhookVerificationResponse,
    'timestamp' : Time,
  });
  const WebhookVerificationStats = IDL.Record({
    'modeMismatched' : IDL.Nat,
    'logs' : IDL.Vec(WebhookVerificationLogEntry),
    'successful' : IDL.Nat,
    'failed' : IDL.Nat,
  });
  const MetaPhoneNumberStatus = IDL.Record({
    'hasAnyNumberAttached' : IDL.Bool,
    'totalNumbers' : IDL.Nat,
    'testNumbers' : IDL.Nat,
    'apiStatusCode' : IDL.Nat,
    'productionNumbers' : IDL.Nat,
  });
  const Example = IDL.Record({ 'body_text' : IDL.Vec(IDL.Text) });
  const TemplateComponent = IDL.Record({
    'example' : IDL.Opt(Example),
    'format' : IDL.Opt(IDL.Text),
  });
  const Language = IDL.Record({ 'code' : IDL.Text, 'policy' : IDL.Text });
  const ExternalWhatsAppTemplate = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'components' : IDL.Vec(TemplateComponent),
    'language' : Language,
    'category' : IDL.Text,
  });
  const MessagePayload = IDL.Record({
    'to' : IDL.Text,
    'content' : IDL.Text,
    'from' : IDL.Text,
  });
  const MetaApiResponse = IDL.Record({
    'deliveryStatus' : MessageStatus,
    'metaMessageId' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TemplateUpdateInput = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'name' : IDL.Text,
  });
  const WebhookVerificationOutcome = IDL.Variant({
    'modeMismatch' : IDL.Null,
    'success' : IDL.Text,
    'invalidToken' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPartnerBenefit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addRecipient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, RecipientType, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTemplate' : IDL.Func([TemplateInput], [IDL.Text], []),
    'deleteSchedule' : IDL.Func([IDL.Text], [], []),
    'deleteTemplate' : IDL.Func([IDL.Text], [], []),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllDailySchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getAllImmediateSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
    'getAllPartnerBenefits' : IDL.Func(
        [],
        [IDL.Vec(PartnerBenefit)],
        ['query'],
      ),
    'getAllSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
    'getAllSubmittedDocuments' : IDL.Func(
        [],
        [IDL.Vec(SubmittedDocument)],
        ['query'],
      ),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(WhatsAppTemplate)], ['query']),
    'getAllWhatsAppMessages' : IDL.Func(
        [],
        [IDL.Vec(WhatsAppMessage)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMetaApiConfig' : IDL.Func([], [MetaApiConfig], []),
    'getOfficeContactData' : IDL.Func([], [OfficeContactData], ['query']),
    'getOnboardingRequirements' : IDL.Func(
        [],
        [IDL.Vec(OnboardingRequirement)],
        ['query'],
      ),
    'getRecipient' : IDL.Func([IDL.Text], [RecipientRecord], ['query']),
    'getSchedule' : IDL.Func([IDL.Text], [Schedule], ['query']),
    'getTemplate' : IDL.Func([IDL.Text], [WhatsAppTemplate], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebhookVerificationStats' : IDL.Func(
        [],
        [IDL.Opt(WebhookVerificationStats)],
        ['query'],
      ),
    'getWhatsAppAccountDetails' : IDL.Func(
        [],
        [IDL.Opt(MetaApiConfig)],
        ['query'],
      ),
    'getWhatsAppIntegrationStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getWhatsAppTokenStatus' : IDL.Func([], [IDL.Text], ['query']),
    'hasAtLeastOnePhoneNumberAttached' : IDL.Func(
        [],
        [MetaPhoneNumberStatus],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMetaTemplates' : IDL.Func([], [IDL.Vec(ExternalWhatsAppTemplate)], []),
    'listRecipients' : IDL.Func([], [IDL.Vec(RecipientRecord)], ['query']),
    'removeRecipient' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleMessage' : IDL.Func(
        [IDL.Text, IDL.Text, ScheduleType, IDL.Opt(Time)],
        [],
        [],
      ),
    'sendWhatsAppMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendWhatsAppMessageViaAPI' : IDL.Func(
        [MessagePayload],
        [MetaApiResponse],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMetaApiConfig' : IDL.Func([MetaApiConfig], [], []),
    'updateOfficeContactData' : IDL.Func([OfficeContactData], [], []),
    'updateTemplate' : IDL.Func([TemplateUpdateInput], [], []),
    'uploadDocument' : IDL.Func([DocumentType, IDL.Text, ExternalBlob], [], []),
    'verifyMetaWebhook' : IDL.Func(
        [MetaWebhookVerificationRequest],
        [WebhookVerificationOutcome],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };