/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const PartnerBenefit = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentType = IDL.Variant({
  'bankDetails' : IDL.Null,
  'mobileNumber' : IDL.Null,
  'selfie' : IDL.Null,
  'email' : IDL.Null,
  'panCard' : IDL.Null,
  'aadhaarCard' : IDL.Null,
  'educationCertificate' : IDL.Null,
});
export const SubmittedDocument = IDL.Record({
  'id' : IDL.Text,
  'fileName' : IDL.Text,
  'fileContent' : ExternalBlob,
  'docType' : DocumentType,
  'uploadedAt' : Time,
});
export const MessageStatus = IDL.Variant({
  'read' : IDL.Null,
  'sent' : IDL.Null,
  'delivered' : IDL.Null,
  'failed' : IDL.Null,
});
export const WhatsAppMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'content' : IDL.Text,
  'recipient' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const MetaApiConfig = IDL.Record({
  'whatsappBusinessAccountId' : IDL.Text,
  'accessToken' : IDL.Text,
  'phoneNumberId' : IDL.Text,
});
export const OfficeContactData = IDL.Record({
  'city' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const OnboardingRequirement = IDL.Record({
  'description' : IDL.Text,
  'required' : IDL.Bool,
  'docType' : DocumentType,
});
export const MetaWebhookVerificationRequest = IDL.Record({
  'challenge' : IDL.Text,
  'verifyToken' : IDL.Text,
  'mode' : IDL.Text,
});
export const MetaWebhookVerificationResponse = IDL.Record({
  'responseBody' : IDL.Text,
  'responseCode' : IDL.Nat,
});
export const WebhookVerificationLogEntry = IDL.Record({
  'request' : MetaWebhookVerificationRequest,
  'response' : MetaWebhookVerificationResponse,
  'timestamp' : Time,
});
export const WebhookVerificationStats = IDL.Record({
  'modeMismatched' : IDL.Nat,
  'logs' : IDL.Vec(WebhookVerificationLogEntry),
  'successful' : IDL.Nat,
  'failed' : IDL.Nat,
});
export const MetaPhoneNumberStatus = IDL.Record({
  'hasAnyNumberAttached' : IDL.Bool,
  'totalNumbers' : IDL.Nat,
  'testNumbers' : IDL.Nat,
  'apiStatusCode' : IDL.Nat,
  'productionNumbers' : IDL.Nat,
});
export const MessagePayload = IDL.Record({
  'to' : IDL.Text,
  'content' : IDL.Text,
  'from' : IDL.Text,
});
export const MetaApiResponse = IDL.Record({
  'deliveryStatus' : MessageStatus,
  'metaMessageId' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const WebhookVerificationOutcome = IDL.Variant({
  'modeMismatch' : IDL.Null,
  'success' : IDL.Text,
  'invalidToken' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPartnerBenefit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getAllPartnerBenefits' : IDL.Func([], [IDL.Vec(PartnerBenefit)], ['query']),
  'getAllSubmittedDocuments' : IDL.Func(
      [],
      [IDL.Vec(SubmittedDocument)],
      ['query'],
    ),
  'getAllWhatsAppMessages' : IDL.Func(
      [],
      [IDL.Vec(WhatsAppMessage)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMetaApiConfig' : IDL.Func([], [MetaApiConfig], []),
  'getOfficeContactData' : IDL.Func([], [OfficeContactData], ['query']),
  'getOnboardingRequirements' : IDL.Func(
      [],
      [IDL.Vec(OnboardingRequirement)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebhookVerificationStats' : IDL.Func(
      [],
      [IDL.Opt(WebhookVerificationStats)],
      ['query'],
    ),
  'getWhatsAppAccountDetails' : IDL.Func(
      [],
      [IDL.Opt(MetaApiConfig)],
      ['query'],
    ),
  'getWhatsAppIntegrationStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getWhatsAppTokenStatus' : IDL.Func([], [IDL.Text], ['query']),
  'hasAtLeastOnePhoneNumberAttached' : IDL.Func(
      [],
      [MetaPhoneNumberStatus],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendWhatsAppMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendWhatsAppMessageViaAPI' : IDL.Func(
      [MessagePayload],
      [MetaApiResponse],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMetaApiConfig' : IDL.Func([MetaApiConfig], [], []),
  'updateOfficeContactData' : IDL.Func([OfficeContactData], [], []),
  'uploadDocument' : IDL.Func([DocumentType, IDL.Text, ExternalBlob], [], []),
  'verifyMetaWebhook' : IDL.Func(
      [MetaWebhookVerificationRequest],
      [WebhookVerificationOutcome],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const PartnerBenefit = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentType = IDL.Variant({
    'bankDetails' : IDL.Null,
    'mobileNumber' : IDL.Null,
    'selfie' : IDL.Null,
    'email' : IDL.Null,
    'panCard' : IDL.Null,
    'aadhaarCard' : IDL.Null,
    'educationCertificate' : IDL.Null,
  });
  const SubmittedDocument = IDL.Record({
    'id' : IDL.Text,
    'fileName' : IDL.Text,
    'fileContent' : ExternalBlob,
    'docType' : DocumentType,
    'uploadedAt' : Time,
  });
  const MessageStatus = IDL.Variant({
    'read' : IDL.Null,
    'sent' : IDL.Null,
    'delivered' : IDL.Null,
    'failed' : IDL.Null,
  });
  const WhatsAppMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'content' : IDL.Text,
    'recipient' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const MetaApiConfig = IDL.Record({
    'whatsappBusinessAccountId' : IDL.Text,
    'accessToken' : IDL.Text,
    'phoneNumberId' : IDL.Text,
  });
  const OfficeContactData = IDL.Record({
    'city' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OnboardingRequirement = IDL.Record({
    'description' : IDL.Text,
    'required' : IDL.Bool,
    'docType' : DocumentType,
  });
  const MetaWebhookVerificationRequest = IDL.Record({
    'challenge' : IDL.Text,
    'verifyToken' : IDL.Text,
    'mode' : IDL.Text,
  });
  const MetaWebhookVerificationResponse = IDL.Record({
    'responseBody' : IDL.Text,
    'responseCode' : IDL.Nat,
  });
  const WebhookVerificationLogEntry = IDL.Record({
    'request' : MetaWebhookVerificationRequest,
    'response' : MetaWebhookVerificationResponse,
    'timestamp' : Time,
  });
  const WebhookVerificationStats = IDL.Record({
    'modeMismatched' : IDL.Nat,
    'logs' : IDL.Vec(WebhookVerificationLogEntry),
    'successful' : IDL.Nat,
    'failed' : IDL.Nat,
  });
  const MetaPhoneNumberStatus = IDL.Record({
    'hasAnyNumberAttached' : IDL.Bool,
    'totalNumbers' : IDL.Nat,
    'testNumbers' : IDL.Nat,
    'apiStatusCode' : IDL.Nat,
    'productionNumbers' : IDL.Nat,
  });
  const MessagePayload = IDL.Record({
    'to' : IDL.Text,
    'content' : IDL.Text,
    'from' : IDL.Text,
  });
  const MetaApiResponse = IDL.Record({
    'deliveryStatus' : MessageStatus,
    'metaMessageId' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const WebhookVerificationOutcome = IDL.Variant({
    'modeMismatch' : IDL.Null,
    'success' : IDL.Text,
    'invalidToken' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPartnerBenefit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getAllPartnerBenefits' : IDL.Func(
        [],
        [IDL.Vec(PartnerBenefit)],
        ['query'],
      ),
    'getAllSubmittedDocuments' : IDL.Func(
        [],
        [IDL.Vec(SubmittedDocument)],
        ['query'],
      ),
    'getAllWhatsAppMessages' : IDL.Func(
        [],
        [IDL.Vec(WhatsAppMessage)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMetaApiConfig' : IDL.Func([], [MetaApiConfig], []),
    'getOfficeContactData' : IDL.Func([], [OfficeContactData], ['query']),
    'getOnboardingRequirements' : IDL.Func(
        [],
        [IDL.Vec(OnboardingRequirement)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebhookVerificationStats' : IDL.Func(
        [],
        [IDL.Opt(WebhookVerificationStats)],
        ['query'],
      ),
    'getWhatsAppAccountDetails' : IDL.Func(
        [],
        [IDL.Opt(MetaApiConfig)],
        ['query'],
      ),
    'getWhatsAppIntegrationStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getWhatsAppTokenStatus' : IDL.Func([], [IDL.Text], ['query']),
    'hasAtLeastOnePhoneNumberAttached' : IDL.Func(
        [],
        [MetaPhoneNumberStatus],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendWhatsAppMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendWhatsAppMessageViaAPI' : IDL.Func(
        [MessagePayload],
        [MetaApiResponse],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMetaApiConfig' : IDL.Func([MetaApiConfig], [], []),
    'updateOfficeContactData' : IDL.Func([OfficeContactData], [], []),
    'uploadDocument' : IDL.Func([DocumentType, IDL.Text, ExternalBlob], [], []),
    'verifyMetaWebhook' : IDL.Func(
        [MetaWebhookVerificationRequest],
        [WebhookVerificationOutcome],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };