/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type DocumentType = { 'bankDetails' : null } |
  { 'mobileNumber' : null } |
  { 'selfie' : null } |
  { 'email' : null } |
  { 'panCard' : null } |
  { 'aadhaarCard' : null } |
  { 'educationCertificate' : null };
export interface Example { 'body_text' : Array<string> }
export type ExternalBlob = Uint8Array;
export interface ExternalWhatsAppTemplate {
  'id' : string,
  'status' : string,
  'name' : string,
  'components' : Array<TemplateComponent>,
  'language' : Language,
  'category' : string,
}
export interface FAQ { 'question' : string, 'answer' : string }
export interface Language { 'code' : string, 'policy' : string }
export interface MessagePayload {
  'to' : string,
  'content' : string,
  'from' : string,
}
export type MessageStatus = { 'read' : null } |
  { 'sent' : null } |
  { 'delivered' : null } |
  { 'failed' : null };
export interface MetaApiConfig {
  'whatsappBusinessAccountId' : string,
  'accessToken' : string,
  'phoneNumberId' : string,
}
export interface MetaApiResponse {
  'deliveryStatus' : MessageStatus,
  'metaMessageId' : string,
}
export interface MetaPhoneNumberStatus {
  'hasAnyNumberAttached' : boolean,
  'totalNumbers' : bigint,
  'testNumbers' : bigint,
  'apiStatusCode' : bigint,
  'productionNumbers' : bigint,
}
export interface MetaWebhookVerificationRequest {
  'challenge' : string,
  'verifyToken' : string,
  'mode' : string,
}
export interface MetaWebhookVerificationResponse {
  'responseBody' : string,
  'responseCode' : bigint,
}
export interface OfficeContactData {
  'city' : string,
  'email' : string,
  'district' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
}
export interface OnboardingRequirement {
  'description' : string,
  'required' : boolean,
  'docType' : DocumentType,
}
export interface PartnerBenefit { 'title' : string, 'description' : string }
export interface RecipientRecord {
  'description' : string,
  'partnerId' : string,
  'phoneNumber' : string,
  'recipientType' : RecipientType,
  'sourceSystem' : string,
}
export type RecipientType = { 'individual' : null } |
  { 'automatedSystem' : null } |
  { 'corporateClient' : null } |
  { 'representative' : null } |
  { 'teamMember' : null };
export interface Schedule {
  'id' : string,
  'messageContent' : string,
  'templateId' : string,
  'runCount' : bigint,
  'lastRunTimestamp' : [] | [Time],
  'templateName' : string,
  'recipients' : Array<RecipientRecord>,
  'scheduleType' : ScheduleType,
  'runAtTimestamp' : [] | [Time],
}
export type ScheduleType = { 'immediate' : null } |
  { 'daily' : null };
export interface SubmittedDocument {
  'id' : string,
  'fileName' : string,
  'fileContent' : ExternalBlob,
  'docType' : DocumentType,
  'uploadedAt' : Time,
}
export interface TemplateComponent {
  'example' : [] | [Example],
  'format' : [] | [string],
}
export interface TemplateInput { 'content' : string, 'name' : string }
export interface TemplateUpdateInput {
  'id' : string,
  'content' : string,
  'name' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebhookVerificationLogEntry {
  'request' : MetaWebhookVerificationRequest,
  'response' : MetaWebhookVerificationResponse,
  'timestamp' : Time,
}
export type WebhookVerificationOutcome = { 'modeMismatch' : null } |
  { 'success' : string } |
  { 'invalidToken' : null };
export interface WebhookVerificationStats {
  'modeMismatched' : bigint,
  'logs' : Array<WebhookVerificationLogEntry>,
  'successful' : bigint,
  'failed' : bigint,
}
export interface WhatsAppMessage {
  'id' : string,
  'status' : MessageStatus,
  'content' : string,
  'recipient' : string,
  'sender' : string,
  'timestamp' : Time,
}
export interface WhatsAppTemplate {
  'id' : string,
  'content' : string,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : [] | [Time],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFAQ' : ActorMethod<[string, string, string], undefined>,
  'addPartnerBenefit' : ActorMethod<[string, string, string], undefined>,
  'addRecipient' : ActorMethod<
    [string, string, string, RecipientType, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTemplate' : ActorMethod<[TemplateInput], string>,
  'deleteSchedule' : ActorMethod<[string], undefined>,
  'deleteTemplate' : ActorMethod<[string], undefined>,
  'getAllContactFormSubmissions' : ActorMethod<
    [],
    Array<ContactFormSubmission>
  >,
  'getAllDailySchedules' : ActorMethod<[], Array<Schedule>>,
  'getAllFAQs' : ActorMethod<[], Array<FAQ>>,
  'getAllImmediateSchedules' : ActorMethod<[], Array<Schedule>>,
  'getAllPartnerBenefits' : ActorMethod<[], Array<PartnerBenefit>>,
  'getAllSchedules' : ActorMethod<[], Array<Schedule>>,
  'getAllSubmittedDocuments' : ActorMethod<[], Array<SubmittedDocument>>,
  'getAllTemplates' : ActorMethod<[], Array<WhatsAppTemplate>>,
  'getAllWhatsAppMessages' : ActorMethod<[], Array<WhatsAppMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMetaApiConfig' : ActorMethod<[], MetaApiConfig>,
  'getOfficeContactData' : ActorMethod<[], OfficeContactData>,
  'getOnboardingRequirements' : ActorMethod<[], Array<OnboardingRequirement>>,
  'getRecipient' : ActorMethod<[string], RecipientRecord>,
  'getSchedule' : ActorMethod<[string], Schedule>,
  'getTemplate' : ActorMethod<[string], WhatsAppTemplate>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebhookVerificationStats' : ActorMethod<
    [],
    [] | [WebhookVerificationStats]
  >,
  'getWhatsAppAccountDetails' : ActorMethod<[], [] | [MetaApiConfig]>,
  'getWhatsAppIntegrationStatus' : ActorMethod<[], string>,
  'getWhatsAppTokenStatus' : ActorMethod<[], string>,
  'hasAtLeastOnePhoneNumberAttached' : ActorMethod<[], MetaPhoneNumberStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMetaTemplates' : ActorMethod<[], Array<ExternalWhatsAppTemplate>>,
  'listRecipients' : ActorMethod<[], Array<RecipientRecord>>,
  'removeRecipient' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleMessage' : ActorMethod<
    [string, string, ScheduleType, [] | [Time]],
    undefined
  >,
  'sendWhatsAppMessage' : ActorMethod<[string, string, string], undefined>,
  'sendWhatsAppMessageViaAPI' : ActorMethod<[MessagePayload], MetaApiResponse>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMetaApiConfig' : ActorMethod<[MetaApiConfig], undefined>,
  'updateOfficeContactData' : ActorMethod<[OfficeContactData], undefined>,
  'updateTemplate' : ActorMethod<[TemplateUpdateInput], undefined>,
  'uploadDocument' : ActorMethod<
    [DocumentType, string, ExternalBlob],
    undefined
  >,
  'verifyMetaWebhook' : ActorMethod<
    [MetaWebhookVerificationRequest],
    WebhookVerificationOutcome
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];